config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pokemons, only: [:index, :show]
  resources :trainers
  resources :teams
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
    has_many :trainer_pokemons
    has_many :trainers, through: :trainer_pokemons

    #this should be class method because we are not calling it on a particular instance
    def self.get_data #scope of this method is the class
        #response will be a string
        response = RestClient.get("https://pokeapi.co/api/v2/pokemon?limit=151")
        #we parse it into a hash
        pokemons = JSON.parse(response)["results"]#add number at end for pokemon

        pokemons.each do |pokemon|
            self.create(name: pokemon["name"])
        end
    end

    def capitalize_name
        self.name.capitalize
    end
end

app/models/team.rb
class Team < ApplicationRecord
    belongs_to :trainer
    POKEMONS = Pokemon.all.collect { |pokemon| pokemon.name.capitalize }
    TRAINERS = Trainer.all.collect { |trainer| trainer.name.split.map(&:capitalize).join(' ') }
end

app/models/trainer.rb
class Trainer < ApplicationRecord
    has_many :teams
    has_many :trainer_pokemons
    has_many :pokemons, through: :trainer_pokemons

    def cap_name
        self.name.split.map(&:capitalize).join(' ')
    end
end

app/models/trainer_pokemon.rb
class TrainerPokemon < ApplicationRecord
    belongs_to :trainer
    belongs_to :pokemon
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
    def index
        #all pokemon listed with number and links to show page
        @pokemons = Pokemon.all
    end

    def show
        #show page for individual pokemon
        @pokemon = Pokemon.find_by(id: params[:id])
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
    def show
        find_team
    end

    def new
        @team = Team.new
    end

    def create
        @team = Team.new(team_params)
        @team.save
    end

    def edit
        find_team
    end

    def update
        find_team
        @team.update(team_params)
    end

    def destroy
    end

    private

    def find_team
        @team = Team.find_by(id: params[:id])
    end

    def team_params
        #need to add more params for pokemon
        params.require(:team).permit(:name)
    end
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
    def index
        #show all trainers and link to their profile
        @trainers = Trainer.all
    end

    def show
        #show trainer profile
        @trainer = Trainer.find_by(id: params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokemonMiniProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pokemons/index.html.erb
<h1> All Pokemon in Kanto Region </h1>

<% @pokemons.each do |pokemon| %>
    <p><%= link_to pokemon.name.capitalize, pokemon_path(pokemon) %></p><br>
<% end %>

app/views/pokemons/show.html.erb
<h1>Trainers of @pokemon.name</h1>

<% @pokemon.trainers.each do |trainer| %>
    <p><%= trainer.name.capitalize if trainer %></p><br>
<% end %>

app/views/trainers/index.html.erb
<% @trainers.all.each do |trainer| %>
    <%= link_to trainer.cap_name, trainer_path(trainer) %><br>
<% end %>

app/views/trainers/show.html.erb
<h1><%= @trainer.name %></h1> <br>

<p><% @trainer.teams.each do |team| %>
    <%= team if team%><br>
<% end %>